name: Microsoft Graph Toolkit New Version Released
on:
  repository_dispatch:
    types: [graph-toolkit-released]
jobs:
  notification:
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Get Release Detail
        id: detail
        uses: actions/github-script@v6
        with:
          script: |
            const responseBody = "<p>Microsoft Graph Toolkit v" + "${{ github.event.client_payload.version }} has been released.\n Details can be found here: https://github.com/microsoftgraph/microsoft-graph-toolkit/releases/tag/v${{ github.event.client_payload.version }}";
            return responseBody;

      - name: Setup Email and Recipient
        id: email
        run: |
          emails="vsciotadt@microsoft.com;junjieli@microsoft.com;zhshang@microsoft.com;donji@microsoft.com;zhany@microsoft.com"
          subject="Microsoft Graph Toolkit v${{ github.event.client_payload.version }} Released"

          echo "to=$emails" >> $GITHUB_OUTPUT
          echo "subject=$subject" >> $GITHUB_OUTPUT
          
      - name: Checkout
        uses: actions/checkout@v3

      - name: Send E-mail Notifications
        uses: ./.github/actions/send-email-report
        env:
          TO: ${{ steps.email.outputs.to }}
          BODY: ${{ steps.detail.outputs.result }}
          SUBJECT: ${{ steps.email.outputs.subject }}
          MAIL_CLIENT_ID: ${{ secrets.TEST_CLEAN_CLIENT_ID }}
          MAIL_CLIENT_SECRET: ${{ secrets.TEST_CLEAN_CLIENT_SECRET }}
          MAIL_TENANT_ID: ${{ secrets.TEST_CLEAN_TENANT_ID }}
